version: "3"
services:
  web:
    build: .
    volumes:
      - .:/sinatra-inhouse-app
      - ruby-bundle:/usr/local/bundle
    working_dir: /sinatra-inhouse-app
    ports:
      - 4567:4567
    command: bundle exec rackup --host 0.0.0.0 --port 4567

volumes:
  ruby-bundle:
    driver: local
